package innoandpatentms.iapms.controller;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import innoandpatentms.iapms.entity.Committee;
import innoandpatentms.iapms.entity.Patent;
import innoandpatentms.iapms.entity.Status;
import innoandpatentms.iapms.entity.User;
import innoandpatentms.iapms.repository.CommitteeRepository;
import innoandpatentms.iapms.repository.PatentRepository;
import innoandpatentms.iapms.repository.UserRepository;
import lombok.RequiredArgsConstructor;

/**
 * Centralized Administrative Controller for project.
 * * CORE FEATURES:
 * 1. Committee Management: Prevents duplicate names and manages member assignments.
 * 2. User & Role Management: Dynamically promotes/demotes users.
 * 3. System Analytics: Real-time metrics for the admin dashboard.
 * 4. Override Decisions: Final approval authority bypassing standard review.
 * * SECURITY: @PreAuthorize("hasRole('ADMIN')") works with the "ROLE_" prefix
 * generated by CustomUserDetailsService.
 */
@RestController
@RequestMapping("/api/v1.0/admin")
@RequiredArgsConstructor
@PreAuthorize("hasAuthority('ADMIN')")
public class AdminController {

    private final UserRepository userRepository;
    private final PatentRepository patentRepository;
    private final CommitteeRepository committeeRepository;

    // ==========================================
    // SECTION 1: COMMITTEE MANAGEMENT
    // ==========================================

    /**
     * Creates a new specialized Review Committee.
     * VALIDATION: Prevents creation if a committee with the same name exists (case-insensitive).
     */
    /**
     * Creates a new specialized Review Committee.
     * ADVANCED VALIDATION: Prevents duplicate meanings (e.g., "AI Board" vs "Board of AI").
     */
@PostMapping("/committees/create")
    public ResponseEntity<?> createCommittee(@RequestBody Committee committee) {
        String inputName = committee.getName().trim();
        String inputFingerprint = generateFingerprint(inputName);

        boolean exists = committeeRepository.findAll().stream()
                .anyMatch(c -> generateFingerprint(c.getName()).equals(inputFingerprint));

        if (exists) {
            return ResponseEntity.badRequest()
                    .body("Error: A committee with a similar meaning already exists.");
        }

        committee.setName(inputName);
        return ResponseEntity.ok(committeeRepository.save(committee));
    }

    private String generateFingerprint(String name) {
        if (name == null) return "";
        String clean = name.toLowerCase().replaceAll("[^a-z0-9\\s]", "");
        List<String> stopWords = Arrays.asList("of", "the", "and", "for", "with", "in", "at");
        
        return Arrays.stream(clean.split("\\s+"))
                .filter(word -> !stopWords.contains(word))
                .sorted()
                .collect(Collectors.joining(" "));
    }
    
    /**
     * Deletes a committee from the system.
     * Logic: Removes associations in the join table first, then deletes the committee.
     */
@DeleteMapping("/committees/delete/{id}")
    @Transactional
    public ResponseEntity<String> deleteCommittee(@PathVariable Long id) {
        Committee committee = committeeRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Committee not found with ID: " + id));

        List<Patent> assignedPatents = patentRepository.findByAssignedCommittee(committee);
        if (!assignedPatents.isEmpty()) {
            return ResponseEntity.badRequest()
                    .body("Cannot delete: This committee is currently reviewing " + assignedPatents.size() + " patents.");
        }

        committee.getMembers().clear();
        committeeRepository.save(committee);
        committeeRepository.delete(committee);

        return ResponseEntity.ok("Committee '" + committee.getName() + "' deleted successfully.");
    }
    /**
     * Assigns a User to a specific Committee group.
     * AUTOMATIC ROLE UPGRADE: Assigns 'REVIEWER' role if the user doesn't have it.
     */
@PostMapping("/committees/{cId}/add-reviewer/{uId}")
    @Transactional
    public ResponseEntity<String> addReviewerToGroup(@PathVariable Long cId, @PathVariable Long uId) {
        Committee committee = committeeRepository.findById(cId)
                .orElseThrow(() -> new RuntimeException("Committee ID " + cId + " not found."));
        
        User user = userRepository.findById(uId)
                .orElseThrow(() -> new RuntimeException("User ID " + uId + " not found."));

        if (!committee.getMembers().contains(user)) {
            committee.getMembers().add(user);
            if (!user.getRoles().contains("REVIEWER")) {
                user.getRoles().add("REVIEWER");
                userRepository.save(user); 
            }
            committeeRepository.save(committee);
        }
        
        return ResponseEntity.ok("Success: User " + user.getFirstName() + " added to " + committee.getName());
    }
@GetMapping("/committees")
    public ResponseEntity<List<Committee>> getAllCommittees() {
        return ResponseEntity.ok(committeeRepository.findAll());
    }

    // ==========================================
    // SECTION 2: USER & ROLE MANAGEMENT
    // ==========================================

    @GetMapping("/users")
    public ResponseEntity<List<User>> getAllUsers() {
        return ResponseEntity.ok(userRepository.findAll());
    }
    /**
     * Toggles specific roles for a user.
     * Note: Input 'role' string should not include "ROLE_" as it's added by the service.
    */
    @PutMapping("/assign-committee-admin/{committeeId}/{userId}")
    @Transactional
    public ResponseEntity<String> assignCommitteeAdmin(
            @PathVariable Long committeeId,
            @PathVariable Long userId,
            @RequestParam boolean add) {
        
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        Committee committee = committeeRepository.findById(committeeId)
                .orElseThrow(() -> new RuntimeException("Committee not found"));
        
        if (userId == 1) {
            return ResponseEntity.badRequest().body("Security: General Admin managed via DB.");
        }

        if (add) {
            // ERROR FIX: Use the plural .getCommittees()
            if (!user.getCommittees().contains(committee)) {
                return ResponseEntity.badRequest().body("User is not a member of this committee.");
            }

            User oldAdmin = committee.getCommitteeAdmin();
            if (oldAdmin != null && !oldAdmin.getId().equals(user.getId())) {
                // ERROR FIX: Use .getRoles() correctly
                oldAdmin.getRoles().remove("COMMITTEE_ADMIN");
                userRepository.save(oldAdmin);
            }

            committee.setCommitteeAdmin(user);
            user.getRoles().add("COMMITTEE_ADMIN");
            committeeRepository.save(committee);
        } else {
            if (user.equals(committee.getCommitteeAdmin())) {
                committee.setCommitteeAdmin(null);
                committeeRepository.save(committee);
                user.getRoles().remove("COMMITTEE_ADMIN");
            }
        }
        
        userRepository.save(user);
        return ResponseEntity.ok("Admin updated for " + committee.getName());
    }

    // ==========================================
    // SECTION 3: SYSTEM OVERRIDE & ANALYTICS
    // ==========================================

    /**
     * Admin Override: Finalizes a patent decision bypassing the committee.
     */
@PutMapping("/decide/{id}")
    @Transactional
    public ResponseEntity<?> adminDecide(
            @PathVariable Long id,
            @RequestParam String status,
            @RequestParam String feedback) {
        
        try {
            Patent p = patentRepository.findById(id)
                    .orElseThrow(() -> new RuntimeException("Patent not found"));
            
            // Validates that the input string actually exists in our Enum
            Status newStatus = Status.valueOf(status.toUpperCase());
            p.setStatus(newStatus); 
            p.setReviewerFeedback("ADMIN OVERRIDE: " + feedback);
            
            return ResponseEntity.ok(patentRepository.save(p));
        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest().body("Invalid status provided. Valid options are: " + Arrays.toString(Status.values()));
        }
    }

    @GetMapping("/stats")
    public ResponseEntity<Map<String, Object>> getStats() {
        Map<String, Object> stats = new HashMap<>();
        stats.put("totalUsers", userRepository.count());
        stats.put("totalCommittees", committeeRepository.count());
        stats.put("totalPatents", patentRepository.count());
        
        // Ensure these methods in PatentRepository accept the Status Enum
        stats.put("pendingPatents", patentRepository.findByStatus(Status.PENDING).size());
        return ResponseEntity.ok(stats);
    }
}